In [208]:
#1. Import the numbpy package under the name np
import numpy as np

In [3]:
#2. Print the numpy version and the configuration
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Insha/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Insha/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Insha/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Insha/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Insha/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Insha/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Insha/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Insha/anaconda3\\Library\\include']


In [79]:
#3. Create a null vector of size 10
R=np.zeros(10)
print (R)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [80]:
#4. How to find the memory size of any array
R= np.zeros((15,15))
print("%d bytes" % (R.size * R.itemsize))

1800 bytes


In [210]:
# How to get the documentation of the numpy add function from the command line
run `python -c "import numpy; numpy.info(numpy.add)"`

SyntaxError: invalid syntax (<ipython-input-210-9cdb5d88c94f>, line 2)

In [81]:
#6. Create a null vector of size 10 but the fifth value which is 1
R = np.zeros(10)
R[4] = 1
print(R)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [82]:
#7. Create a vector with values ranging from 10 to 49
R = np.arange(10,50)
print (R)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [84]:
#8. Reverse a vector( first element becomes last)
R = np.arange(20)
R = R[::-1]
print(R)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [85]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
R=np.arange(9).reshape(3,3)
print(R)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [86]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
R=np.nonzero([1,2,0,0,4,0])
print(R)

(array([0, 1, 4], dtype=int64),)


In [87]:
#11. Create a 3x3 identity matrix
R=np.eye(3)
print(R)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [88]:
#12. Create a 3x3x3 array with random values
R=np.random.random((3,3,3))
print(R)

[[[0.50802133 0.27229207 0.83962785]
  [0.43206486 0.05184196 0.29876569]
  [0.00553181 0.66005046 0.97757816]]

 [[0.17969525 0.45509566 0.87789604]
  [0.01464913 0.42156138 0.06420388]
  [0.43336567 0.78864545 0.85537025]]

 [[0.71004085 0.84439328 0.62181487]
  [0.64692437 0.89881173 0.8823197 ]
  [0.35074455 0.96535017 0.32493029]]]


In [90]:
#13. Create a 10x10 arrat with random value and find the minimum and maximum values
R=np.random.random((10,10))
Rmn, Rmx=R.min(), R.max()
print(Rmn,Rmx)

0.009124797537419571 0.9985348847069483


In [91]:
#14. Create a random vector of size 30 and find the mean value
R=np.random.random(30)
m=R.mean()
print(m)

0.40565802345749996


In [92]:
#15. Create a 2d array with 1 on the border and 0 inside 
R=np.ones((10,10))
R[1:-1,1:-1] = 0
print (R)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [93]:
#16. How to add a border(filled with 0's) around an existing array?
R = np.ones((15,15))
R = np.pad(R, pad_width=1, mode='constant', constant_values=0)
print(R)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [52]:
#17. What is the result of the following expression
# Adding the print command infront of each of them gives:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)



nan
False
False
nan
True
False


In [94]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
R = np.diag(1+np.arange(4),k =-1)
print(R)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [95]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
R= np.zeros((8,8),dtype=int)
R[1::2,::2] = 1
R[::2,1::2] = 1
print(R)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [203]:
#20. Consider a (6,7,8) shape array, what is the index(x,y,z) of the 100th element?
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [96]:
#21. Create a checkerboard 8x8 matrix using the tile function
R = np.tile (np.array([[0,1],[1,0]]), (4,4))
print(R)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [97]:
#22. Normalize a 5x5 random matrix
R = np.random.random((5,5))
R = (R-np.mean(R))/(np.std(R))
print(R)

[[-1.52979044  0.01857737  1.01538481  0.76951612  0.45475159]
 [ 1.5195554   0.52981627 -1.67030402 -1.21004871 -0.25748612]
 [ 1.31048331 -0.69897837 -0.81070719  1.1722971   1.14485273]
 [-1.58818184 -0.37521613  0.56795153 -0.01209757  0.2410342 ]
 [-0.66788946  0.3454421  -1.45468473 -0.39270824  1.57843027]]


In [212]:
#23. Create a custom dtype that describes a colour as four unsigned bytes(RGBA)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [98]:
#24. Multiply a 5x3 matrix by a 3x2 matrix( real matrix product)
R = np.dot(np.ones((5,3)), np.ones((3,2)))
print(R)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [214]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place
R = np.arange(11)
R[(3<R) & (R<=8)] *= -1
print(R)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [80]:
#26. What is the output of the following script?
#Author:Jake VanderPlas
print(sum(range(5),-1))
from numpy import*
print(sum(range(5),-1))

9
10


In [217]:
#27. Consider an integer vector Z, which of these expressions are legal?
#Z**Z
#Z<-Z
#1j*Z
#Z/1/1
#Z<Z>Z

In [92]:
#28. What is the result of the following expressions?
#Using print command for each of them gives:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-92-d5d689649c64>:3: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0)/np.array(0))
<ipython-input-92-d5d689649c64>:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))


In [101]:
#29. How to round away from zero a float array?
R = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(R)), R))


[-9. -4. -6. -7. -1. -7. -9. -3.  5.  2.]


In [102]:
#30. How to find common values between two arrays?
R1 = np.random.randint(0,10,10)
R2 = np.random.randint(0,10,10)
print(np.intersect1d(R1,R2))

[0 5 7 8 9]


In [104]:
#31. How to ignore all numby warnings (not recommended)?
defaults = np.seterr(all= "ignore")
R = np.ones(1)/0
_ = np.seterr(**defaults)

#with a context manager
with np.errstate(all='ignore'):
    np.arange(3)/0

In [218]:
#32. Is the following expressions true?
print(np.sqrt(-1)==np.emath.sqrt(-1))

False


<ipython-input-218-41b21578ae12>:2: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1)==np.emath.sqrt(-1))


In [108]:
#33. How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today','D')
tomorrow = np.datetime64('today', 'D')+np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)


2021-09-09
2021-09-10
2021-09-11


In [105]:
#34. How to get all the dates correspoding to the month of July 2016?
R=np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(R)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [106]:
#35. How to compute((A+B)*(-A/2)) in place (without copy)?
A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B, out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B, out=A)

array([-1.5, -1.5, -1.5])

In [107]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods?
R=np.random.uniform(0,10,10)
print(R-R%1)
print(np.trunc(R))
print(np.ceil(R)-1)
print(np.floor(R))

[1. 4. 3. 3. 7. 9. 4. 4. 3. 2.]
[1. 4. 3. 3. 7. 9. 4. 4. 3. 2.]
[1. 4. 3. 3. 7. 9. 4. 4. 3. 2.]
[1. 4. 3. 3. 7. 9. 4. 4. 3. 2.]


In [108]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4
R = np.zeros((5,5))
R+= np.arange(5)
print(R)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [112]:
#38. Consider a generator function that generates 10 integers and use it to build an array
def generate():
    for x in range(10):
        yield x
R = np.fromiter(generate(),dtype=float,count=-1)
print(R)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [113]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
R = np.linspace(0,1,11,endpoint=False)[1:]
print(R)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [114]:
#40. Create a random vector of size 10 and sort it
R=np.random.random(10)
R.sort()
print(R)

[0.13011851 0.19986774 0.27143099 0.42709954 0.44820877 0.73167434
 0.81832695 0.89234511 0.93948307 0.96848063]


In [115]:
#41. How to sum a small array faster than np.sum?
R=np.arange(25)
np.add.reduce(R)

300

In [116]:
#42. Consider two random array A and B, check if they are equal
A = np.random.randint(3,6,2)
B = np.random.randint(3,6,2)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)

False
False


In [117]:
#43. Make an immutable(read-only)
R= np.zeros(10)
R.flags.writeable = False
R[0] = 1


ValueError: assignment destination is read-only

In [119]:
#44. Consider a randoM, 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
R= np.random.random((10,2))
X,Y = R[:,0], R[:,1]
B = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(B)
print(T)

[1.21527589 0.65243141 0.97151846 0.98148469 0.62845079 1.07650059
 0.93107537 1.03010582 0.2562969  1.0588769 ]
[0.61412244 0.71045747 1.48589173 0.21116577 1.29505547 0.4137126
 0.54893111 0.25984201 0.69007096 0.60032961]


In [120]:
#45. Create random vector of size 10 and replace the maximum value by 0
R = np.random.random(10)
R[R.argmax()] = 0
print(R)

[0.45470305 0.305598   0.08388824 0.03980955 0.4792142  0.36394922
 0.95311749 0.         0.29970884 0.0055359 ]


In [122]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1area]
R = np.zeros((5,5), [('x', float),('y', float)])
R['x'], R['y'] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
print(R)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [136]:
#47. Given two arrays, X and Y construct the Cauchy matrix C (Cij=1/(xi-yj))
X = np.arange(8)
Y= X+0.5
C=1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


In [123]:
#48.Print the minimum and maximum representable value for each numpy scalar type
#integer type:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
#float type:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [124]:
#49. How to print all the values of an array?
np.set_printoptions(threshold=float("inf"))
R = np.zeros((15,15))
print(R)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [126]:
#50. How to find the closest value(to a given scalar) in a vector?
R=np.arange(15)
u=np.random.uniform(0,15)
index = (np.abs(R-u)).argmin()
print(R[index])

13


In [215]:
#51. Create a structured array representing a psoition(x,y) and a color(r,g,b)
R = np.zeros(10, [('position', [ ('x', float),
                                ('y', float)]),
                  ('color',  [('r', float),
                              ('g', float),
                              ('b', float)])])
print(R)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [133]:
#52. Consider a random vector with shape(100,2) representing coordinates, find point by point distances

R = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

R = np.random.random((10,2))
D = scipy.spatial.distance.cdist(R,R)
print(D)

[[0.         0.93003863 0.49490931 0.56643118 0.50141963 0.37255206
  0.40781538 0.7587072  0.47370507 0.48329101]
 [0.93003863 0.         0.43693827 0.46266802 0.63323833 0.55950641
  0.81458159 0.41379523 0.56731945 0.55275741]
 [0.49490931 0.43693827 0.         0.24947242 0.31254098 0.13616755
  0.48636856 0.35642525 0.27401294 0.20989831]
 [0.56643118 0.46266802 0.24947242 0.         0.55789441 0.24185513
  0.35275132 0.57321902 0.11066156 0.45674774]
 [0.50141963 0.63323833 0.31254098 0.55789441 0.         0.35199853
  0.70367577 0.29798812 0.55508904 0.10291485]
 [0.37255206 0.55950641 0.13616755 0.24185513 0.35199853 0.
  0.36993308 0.47699018 0.20679666 0.26347019]
 [0.40781538 0.81458159 0.48636856 0.35275132 0.70367577 0.36993308
  0.         0.8417988  0.24813835 0.62745352]
 [0.7587072  0.41379523 0.35642525 0.57321902 0.29798812 0.47699018
  0.8417988  0.         0.62540505 0.27638498]
 [0.47370507 0.56731945 0.27401294 0.11066156 0.55508904 0.20679666
  0.24813835 0.62540

In [134]:
#53. How to convert a float(32 bits) array into an integer(32 bits) in place?
R = np.arange(10, dtype=np.float32)
R=R.astype(np.int32, copy=False)
print(R)

[0 1 2 3 4 5 6 7 8 9]


In [135]:
#54. How to read the following file?
from io import StringIO
s = StringIO("""1,2,3,4,5\n
                6, , ,7,8\n""")
R=np.genfromtxt(s, delimiter=",", dtype=int)
print(R)


[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]]


In [136]:
#55. What is the equivalent of enumerate for numpy arrays?
R= np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(R):
        print(index,value)
for index in np.ndindex(R.shape):
    print(index, R[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [137]:
#56. Generate a generic 2D Gaussian-like array
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D= np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D-mu)**2/ (2.0*sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [138]:
#57. How to randomly place p elements in a 2D array
n = 15
p = 4
R = np.zeros((n,n))
np.put(R, np.random.choice(range(n*n), p, replace = False),1)
print(R)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [139]:
#58. Subtract the mean of each row of a matrix?
A = np.random.rand(5, 10)
B = A -A.mean(axis=1, keepdims= True)
B = A -A.mean(axis=1).reshape(-1,1)
print(B)

[[-0.43283028 -0.28858826  0.44900245 -0.38559745  0.13152249  0.41313581
   0.10307655  0.15678727 -0.14349269 -0.00301588]
 [-0.32837515 -0.27674771 -0.41233945  0.32427812 -0.07047727  0.33343278
   0.35556513  0.21185973  0.19229443 -0.3294906 ]
 [ 0.112978   -0.11444482 -0.011869    0.04931756 -0.12591318 -0.34074337
  -0.05260624  0.21574389 -0.29549489  0.56303205]
 [-0.17679167 -0.04686274  0.22744093 -0.20079124 -0.04093745  0.40741804
  -0.09316465 -0.34148569  0.00616364  0.25901083]
 [ 0.30315954  0.47084949  0.16378794 -0.28856902 -0.17081368 -0.01661412
  -0.39482674  0.23849448  0.08048678 -0.38595467]]


In [140]:
#59. How to sort an array by the nth column?
R = np.random.randint(0,10,(3,3))
print(R)
print(R[R[:,1].argsort()])

[[3 6 4]
 [6 5 3]
 [6 7 9]]
[[6 5 3]
 [3 6 4]
 [6 7 9]]


In [141]:
#60. How to tell if a given 2D array has null columns?
R = np.random.randint(0,3,(3,10))
print((~R.any(axis=0)).any())

False


In [142]:
#61. Find the nearest value from a given value in an array
R = np.random.uniform(0,1,10)
z=0.5
x = R.flat[np.abs(Z-z).argmin()]
print(x)

0.28399954669980054


In [144]:
#62. Considering two arrays with shape (1,3) and (3,1), how do compute their sum using an iterator?
P = np.arange(3).reshape(3,1)
Q=np.arange(3).reshape(1,3)
it = np.nditer([P,Q,None])
for x,y,z in it: z[...]= x+y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [145]:
#63. Create an array class that has a name attribute
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

R = NamedArray(np.arange(10), "range_10")
print (R.name)


range_10


In [152]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector(be careful with repeated indices)
A = np.ones(10)
print(A)
B = np.random.randint(0,len(A),20)
A += np.bincount(B, minlength=len(A))
print(A)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4. 2. 4. 3. 2. 2. 5. 3. 2. 3.]


In [153]:
#65. How yo accumulate elements of a vector (X) to an array(F) based on an index list(I)?

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [154]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
c = len(colors)
print(c)

64


In [155]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once?
B = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = B.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = B.reshape(B.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[51 59 52 57]
 [47 70 61 57]
 [52 58 39 42]]
[[51 59 52 57]
 [47 70 61 57]
 [52 58 39 42]]


In [156]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? 
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.44418873 0.65039257 0.66027169 0.54386004 0.61022932 0.34382735
 0.51000142 0.43151887 0.45255219 0.73972589]
0    0.444189
1    0.650393
2    0.660272
3    0.543860
4    0.610229
5    0.343827
6    0.510001
7    0.431519
8    0.452552
9    0.739726
dtype: float64


In [157]:
#69. How to get the diagonal of a dot product?
P = np.random.uniform(0,1,(5,5))
Q = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(P, Q))

# Fast version
np.sum(P * Q.T, axis=1)

# Faster version
np.einsum("ij,ji->i", P, Q)

array([2.25250184, 1.99313002, 0.91319349, 1.15659828, 2.10801558])

In [158]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [159]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
P = np.ones((5,5,3))
Q = 2*np.ones((5,5))
print(P * Q[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [160]:
#72. How to swap two rows of an array?
P = np.arange(25).reshape(5,5)
P[[0,1]] = P[[1,0]]
print(P)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [161]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
U = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
U = np.unique(U)
print(U)

[( 2, 31) ( 2, 87) ( 6, 44) ( 6, 64) ( 7, 21) ( 7, 83) ( 8, 23) ( 8, 56)
 (12, 61) (12, 78) (18, 19) (18, 71) (19, 71) (21, 83) (23, 23) (23, 56)
 (23, 76) (25, 32) (25, 42) (31, 87) (32, 42) (37, 69) (37, 73) (44, 64)
 (61, 78) (69, 73) (73, 78) (73, 81) (78, 81)]


In [45]:
#74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C?
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [162]:
#75. How to compute averages using a sliding window over an array? 
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
R = np.arange(20)
print(moving_average(R, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [163]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(np.arange(10), 3)
print(R)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [164]:
#77. How to negate a boolean, or to change the sign of a float inplace?
R = np.random.randint(0,2,100)
np.logical_not(R, out=R)

R = np.random.uniform(-1.0,1.0,100)
np.negative(R, out=R)

array([-0.36690789, -0.3602045 ,  0.28903017,  0.1664868 ,  0.5366267 ,
        0.92449631, -0.01836049,  0.94109532,  0.31181679,  0.22340828,
       -0.17941889,  0.59369847, -0.57761357, -0.7834708 , -0.45241549,
       -0.82377481, -0.11200468, -0.42379582, -0.5943805 ,  0.34293626,
        0.10547365,  0.2083845 , -0.38723661, -0.37762431, -0.42341319,
        0.96475995,  0.10892982,  0.55932049,  0.22536686,  0.02205389,
       -0.05890571, -0.48179634, -0.58067873,  0.07281543,  0.20380356,
       -0.14172822, -0.35866612, -0.00515065, -0.9178546 ,  0.8718258 ,
        0.03191815,  0.27267594, -0.48983581,  0.30613778, -0.69144211,
        0.27763723,  0.4745923 , -0.46279163,  0.52262812, -0.46662069,
       -0.26379039,  0.85246575,  0.90022682,  0.98867227,  0.24692339,
       -0.17745119, -0.80318189,  0.41302007,  0.28600759,  0.42824199,
       -0.80077377,  0.43835088,  0.38542231,  0.18652199, -0.23208136,
       -0.05180392, -0.8687313 ,  0.07366862, -0.39416508,  0.19

In [166]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[0.0719824  7.91239249 7.32190749 0.11649071 8.75967127 3.20940679
 5.92914552 3.40540327 2.33263173 1.51287667]


In [167]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? 
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 9.73184082  3.51558622 11.16025593  0.19851722  3.62743214  4.52261079
   3.15914455  8.71343487 10.79217073  2.80384606]
 [ 5.40905612  1.27236949  0.12711209  3.75072868 10.97838559  0.09552876
   1.50347433  5.06869453  0.41020646 11.97730008]
 [ 1.34873831  5.30308033  8.17799552  2.35787011 11.57705708  6.53820587
   6.83157477  3.24620924  1.6992821   6.14272492]
 [ 0.56233685  4.81127921  0.24723731  7.78198626  4.19228581  3.59123058
   3.21027212  3.12911008  6.47850136  6.3742997 ]
 [ 1.0820485   1.12088289  2.20288792  3.97561621  7.81399378  0.13612662
   0.71849925  1.72315324  3.58367054  7.54401729]
 [ 7.84973562  4.08922193  3.45201509  6.40740569 10.3757935   2.67618874
   0.8778849   8.28721877  0.88421902 14.00859178]
 [ 5.91548465  7.02576104  1.44385669 10.60651013  2.6789053   5.98728334
   6.90957526  0.68937276 14.04742082  0.68210201]
 [ 5.67863295  4.33942873  2.52305841  6.85268543  8.50289871  2.98411426
   1.60904135  6.76758982  1.33217374 11.72811169]


In [170]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 7 3 4 3 0 8 8 1 1]
 [8 0 7 6 5 7 2 2 6 9]
 [0 4 0 7 9 2 0 8 4 8]
 [4 1 7 0 6 8 9 3 4 5]
 [6 5 9 9 3 0 5 7 1 6]
 [0 8 1 9 2 0 8 7 9 2]
 [7 7 4 9 7 3 7 5 9 8]
 [2 9 7 6 9 6 4 3 0 6]
 [4 4 6 5 8 5 5 8 7 2]
 [8 2 4 0 9 6 7 7 6 5]]
[[0 0 0 0 0]
 [0 6 7 3 4]
 [0 8 0 7 6]
 [0 0 4 0 7]
 [0 4 1 7 0]]


<ipython-input-170-77574ef87a8e>:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [52]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [172]:
#82. Compute a matrix rank

R = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(R) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [175]:
#83. How to find the most frequent value in an array?
R = np.random.randint(0,10,50)
print(np.bincount(R).argmax())

5


In [176]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
R = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (R.shape[0]-3)
j = 1 + (R.shape[1]-3)
C = stride_tricks.as_strided(R, shape=(i, j, n, n), strides=R.strides + R.strides)
print(C)

[[[[0 4 0]
   [0 1 0]
   [1 3 3]]

  [[4 0 0]
   [1 0 3]
   [3 3 0]]

  [[0 0 4]
   [0 3 1]
   [3 0 0]]

  [[0 4 2]
   [3 1 1]
   [0 0 1]]

  [[4 2 3]
   [1 1 4]
   [0 1 2]]

  [[2 3 0]
   [1 4 3]
   [1 2 0]]

  [[3 0 1]
   [4 3 2]
   [2 0 0]]

  [[0 1 1]
   [3 2 0]
   [0 0 2]]]


 [[[0 1 0]
   [1 3 3]
   [2 2 2]]

  [[1 0 3]
   [3 3 0]
   [2 2 3]]

  [[0 3 1]
   [3 0 0]
   [2 3 1]]

  [[3 1 1]
   [0 0 1]
   [3 1 0]]

  [[1 1 4]
   [0 1 2]
   [1 0 1]]

  [[1 4 3]
   [1 2 0]
   [0 1 0]]

  [[4 3 2]
   [2 0 0]
   [1 0 0]]

  [[3 2 0]
   [0 0 2]
   [0 0 2]]]


 [[[1 3 3]
   [2 2 2]
   [4 4 2]]

  [[3 3 0]
   [2 2 3]
   [4 2 4]]

  [[3 0 0]
   [2 3 1]
   [2 4 3]]

  [[0 0 1]
   [3 1 0]
   [4 3 0]]

  [[0 1 2]
   [1 0 1]
   [3 0 0]]

  [[1 2 0]
   [0 1 0]
   [0 0 4]]

  [[2 0 0]
   [1 0 0]
   [0 4 1]]

  [[0 0 2]
   [0 0 2]
   [4 1 0]]]


 [[[2 2 2]
   [4 4 2]
   [4 1 3]]

  [[2 2 3]
   [4 2 4]
   [1 3 1]]

  [[2 3 1]
   [2 4 3]
   [3 1 3]]

  [[3 1 0]
   [4 3 0]
   [1 3 0]]

  [[1 0 1]
   

In [59]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


[[ 7  7  8 16  9]
 [ 7  1 10 16  8]
 [ 8 10  3 42 11]
 [16 16 42  2  8]
 [ 9  8 11  8  4]]


In [177]:
#86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) 
p, n = 10, 20
A = np.ones((p,n,n))
B = np.ones((p,n,1))
S = np.tensordot(A, B, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [178]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
R = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(R, np.arange(0, R.shape[0], k), axis=0),
                                       np.arange(0, R.shape[1], k), axis=1)
print(S)

# alternative solution:
# Author: Sebastian Wallkötter (@FirefoxMetzger)

R = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(R, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [180]:
#88. How to implement the Game of Life using numpy arrays?
def iterate(R):
    # Count neighbours
    N = (R[0:-2,0:-2] + R[0:-2,1:-1] + R[0:-2,2:] +
         R[1:-1,0:-2]                + R[1:-1,2:] +
         R[2:  ,0:-2] + R[2:  ,1:-1] + R[2:  ,2:])

   
    birth = (N==3) & (R[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (R[1:-1,1:-1]==1)
    R[...] = 0
    R[1:-1,1:-1][birth | survive] = 1
    return R

R = np.random.randint(0,2,(50,50))
for i in range(100): R = iterate(R)
print(R)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [183]:
#89. How to get the n largest values of an array
R = np.arange(10000)
np.random.shuffle(R)
n = 5

# Slow
print (R[np.argsort(R)[-n:]])

# Fast
print (R[np.argpartition(-R,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9999 9996 9997 9998]


In [184]:
#90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [186]:
#91. How to create a record array from a regular array?
P = np.array([("Hello", 2.5, 3),
              ("World!", 3.6, 2)])
Q = np.core.records.fromarrays(P.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(Q)

[(b'Hello', 2.5, 3) (b'World!', 3.6, 2)]


In [193]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods
z = np.random.rand(int(5e7))

%timeit np.power(z,3)
%timeit z*z*z
%timeit np.einsum('i,i,i->i',z,z,z)

1.26 s ± 21.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
269 ms ± 15 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
147 ms ± 3.76 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [69]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 7]


In [194]:
#94. Considering a 10x3 matrix, extract rows with unequal values
R = np.random.randint(0,5,(10,3))
print(R)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(R[:,1:] == R[:,:-1], axis=1)
U = R[~E]
print(U)
# solution for numerical arrays only, will work for any number of columns in Z
U = R[R.max(axis=1) != R.min(axis=1),:]
print(U)

[[3 2 4]
 [0 3 3]
 [3 3 0]
 [4 4 2]
 [1 4 2]
 [4 0 0]
 [3 4 3]
 [3 3 3]
 [1 2 4]
 [1 0 4]]
[[3 2 4]
 [0 3 3]
 [3 3 0]
 [4 4 2]
 [1 4 2]
 [4 0 0]
 [3 4 3]
 [1 2 4]
 [1 0 4]]
[[3 2 4]
 [0 3 3]
 [3 3 0]
 [4 4 2]
 [1 4 2]
 [4 0 0]
 [3 4 3]
 [1 2 4]
 [1 0 4]]


In [198]:
#95. Convert a vector of ints into a matrix binary representation
I = np.array([0, 77, 9, 6, 15, 17, 32, 63, 158])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 1 0 0 1 1 0 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [0 0 1 1 1 1 1 1]
 [1 0 0 1 1 1 1 0]]


In [199]:
#96. Given a two dimensional array, how to extract unique rows?
R = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(R).view(np.dtype((np.void, R.dtype.itemsize * R.shape[1])))
_, idx = np.unique(T, return_index=True)
uR = R[idx]
print(uR)


[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]]


In [75]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.5142036 , 0.3075406 , 0.34814548, 0.53777121, 0.40382435,
        0.2196706 , 0.42295236, 0.75729127, 0.48696804, 0.47619888],
       [0.49531803, 0.29624531, 0.33535886, 0.51802005, 0.38899276,
        0.21160258, 0.40741824, 0.72947762, 0.46908277, 0.45870914],
       [0.35530362, 0.21250393, 0.24056103, 0.37158833, 0.27903393,
        0.15178766, 0.29225097, 0.52327197, 0.33648443, 0.32904318],
       [0.17050391, 0.10197687, 0.11544098, 0.17831866, 0.13390344,
        0.07284021, 0.14024607, 0.25110895, 0.16147292, 0.15790199],
       [0.11674323, 0.06982309, 0.0790419 , 0.12209395, 0.09168306,
        0.04987335, 0.09602582, 0.17193312, 0.11055975, 0.10811475],
       [0.32482263, 0.19427353, 0.21992365, 0.33971029, 0.25509601,
        0.13876601, 0.26717918, 0.47838121, 0.30761791, 0.30081503],
       [0.12610665, 0.07542326, 0.08538147, 0.13188652, 0.09903652,
        0.05387345, 0.1037276 , 0.18572305, 0.11942722, 0.11678612],
       [0.5418542 , 0.32407818, 0.3668665

In [200]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [201]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [207]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).
X = np.random.randn(100) # random 1D array
Y = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (Y, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.24761243  0.15390033]
